### PR TITLE
Adds test for text type

### PR DESCRIPTION
**Pull request by lukecampbell**
I'm not sure if TextType is the right parameter type to use but I can't seem to get text type / string types correctly persisted.

### CODE REVIEW

**Comment by lukecampbell** [comment]
@caseybryant can you look this over and see if there's something obvious I'm doing incorrectly?

**Comment by lukecampbell** [comment]
After looking at it, I think `RecordType` does this already.  What do you think, can we just use RecordType for string and blob types?

**Comment by caseybryant** [comment]
I think you are correct, we can use record type. 

I don't think text type is implemented right. I couldn't get it to work and didn't see any tests using it. 

Everything I saw with strings used RecordType or ArrayType with objects as the dtype/value encoding.

**Comment by lukecampbell** [comment]
Ok, I'm just going to use record types then, thanks

**Pull request closed without merging**
