### PR TITLE
External Parameters Implemented

### PR DESCRIPTION
**Pull request by caseybryant**
This pull request replaces PR #155

### CODE REVIEW

**Comment by caseybryant** [comment]
@lukecampbell Want to take a look at this and try it out?

**Comment by lukecampbell** [comment]
I'm looking at it now, looks good.

**Comment by caseybryant** [comment]
The idea is that we move the interpolation function out of coverage purview so you can do whatever you want with it.  I provided a linear interpolation default inside of coverage that you can use/modify for now.

If you like it, I will add the ability to ask for next X number of data points on each side of the window to help with interpolation.  I didn't add it already because I'm still working out some edge cases.

**Comment by lukecampbell** [comment]
Looks good, let me know when I can merge it. My plan is to have it merged soon (if we can) and then I'll have Bob work on M086 which leverages the ability to reference data within adjacent datasets. He'll take over the rest of this integration effort into coi-services.

**Comment by caseybryant** [comment]
You can merge as-is.  I can check something in for the edge cases later.  I'll make an issue to have coverage support collecting neighboring temporal data-points.

**Comment by lukecampbell** [comment]
Awesome!

**Pull request merged**
