### PR TITLE
M117 Interface Changes for Testing

### PR DESCRIPTION
**Pull request by caseybryant**
Interface changes to test coi-services against.

### CODE REVIEW

**Comment by lukecampbell** [comment]
Could we update coverage_model/**init**.py to include imports that are common in the submodule, like `NumpyParameterData`?

It makes it easier to interface with CM if the common imports are at the root of the module.

**Comment by lukecampbell** [comment]
Is there a way using get_parameter_values to get dense arrays filled in with fill values for parameters that don't have data?

**Comment by caseybryant** [comment]
It should insert fill values for elements that don't have data.  Are you asking if we can provide an entire array with filled values if the element did not have any data at all?

**Comment by lukecampbell** [comment]
Yeah, that would be helpful.

**Comment by lukecampbell** [comment]
I'm going to move these into issues on github. I realize that it's yet one more obscure piece of project management that we'll be using but for a fast turn around that's not terribly complicated it's probably the best.

**Comment by lukecampbell** [comment]
https://github.com/ooici/coverage-model/issues/160
https://github.com/ooici/coverage-model/issues/161

**Comment by lukecampbell** [comment]
:+1: Thanks for all the hard work, I think as-is we can integrate it with coi-services and I should be able to close 193 this week, hopefully tomorrow.

**Pull request merged**
